### PR TITLE
add bower.json

### PR DESCRIPTION
**Pull request by A-Zak**
Feel free to update the default authors/homepage and stuffs... :)

### CODE REVIEW

**Comment by young** [comment]
Thanks!

**Comment by A-Zak** [comment]
Would you mind publishing it on bower? would really help me keep my build automated... :)

**Comment by young** [comment]
Sure thing. I'll publish it later tonight.

**Comment by A-Zak** [comment]
:+1:  :)

**Comment by young** [comment]
Done! Updated readme

**Comment by A-Zak** [comment]
Amazing, thanks... :)

**Pull request merged**
